(******************************************************************************)
(*                                                                            *)
(*                    Quadratic Reciprocity: Legendre Symbols                 *)
(*                                                                            *)
(*     Formalizes the Law of Quadratic Reciprocity: for odd primes p ≠ q,     *)
(*     (p/q)(q/p) = (-1)^((p-1)/2 · (q-1)/2). Defines Legendre symbol,        *)
(*     Euler's criterion, quadratic residues. Proves first and second         *)
(*     supplements: (-1/p) = (-1)^((p-1)/2), (2/p) = (-1)^((p²-1)/8).         *)
(*                                                                            *)
(*     "The fundamental theorem, if we consider both its elegance and the     *)
(*     endless applications of which it is capable, deserves without doubt    *)
(*     to be placed among the most beautiful of all of arithmetic."           *)
(*     - Carl Friedrich Gauss, Disquisitiones Arithmeticae, 1801              *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: January 8, 2026                                                  *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
